module.exports = {
    IS_USER:"IS_USER",
    NEW_USER:"NEW_USER",
    INIT_CHATS:"INIT_CHATS",
    LOGOUT:"LOGOUT",
    MESSAGE_SEND:"MESSAGE_SEND",
    TYPING:"TYPING", 
    P_MESSAGE_SEND:"P_MESSAGE_SEND",
    P_TYPING:"P_TYPING",
    CHECK_CHANNEL:"CHECK_CHANNEL",
    CREATE_CHANNEL:"CREATE_CHANNEL",

    TYPE_WHEEL: "TYPE_WHEEL",
    P_TYPE_WHEEL: "P_TYPE_WHEEL",

    RESULT_WHEEL: "RESULT_TYPE",
    P_RESULT_WHEEL: "P_RESULT_WHEEL"
}